apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "planetarium-deployment"
  namespace: "default"
  labels:
    app: "planetarium"
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: "planetarium"
  template: 
    metadata: 
      labels:
        app: "planetarium"
    spec:
      # terminationGracePeriodSeconds: 30
      containers:
      - name: "planetarium-app"
        image: "oloringray007/planetarium:8"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080