apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "planetarium-deployment"
  namespace: "default"
  labels:
    app: "planetarium"
spec: 
  replicas: 1
  selector:
    matchLabels:
      pod: "planetarium-pod"
  template: 
    metadata: 
      labels:
        pod: "planetarium-pod"
    spec:
      containers:
      - name: "planetarium-app"
        image: "oloringray007/planetarium:8"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080